# Generated by Django 6.0 on 2025-12-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_actorimage_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieframe',
            name='image_en',
            field=models.ImageField(null=True, upload_to='movie_images'),
        ),
        migrations.AddField(
            model_name='movieframe',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='movie_images'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movie_app.category'),
        ),
    ]
