# Generated by Django 6.0 on 2025-12-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movieframe_image_en_movieframe_image_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_status',
            new_name='status',
        ),
    ]
