# Generated by Django 6.0 on 2025-12-23 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_rename_movie_status_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor_movies', to='movie_app.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movies', to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(upload_to='movie_poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('pro', 'pro'), ('simple', 'simple')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='image',
            field=models.ImageField(upload_to='movie_frame'),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='image_en',
            field=models.ImageField(null=True, upload_to='movie_frame'),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='movie_frame'),
        ),
        migrations.AlterField(
            model_name='movieframe',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='video',
            field=models.FileField(upload_to='video_video'),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='video_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='video_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movievideo',
            name='video_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user=images'),
        ),
    ]
